name: Maven Caching Test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        # DÒNG QUAN TRỌNG NHẤT CỦA BÀI 6 NẰM Ở ĐÂY:
        cache: 'maven'

    - name: Build Project
      run: mvn clean compile